doctrine_migrations:
    migrations_paths:
        'App\Infrastructure\Migration': '%kernel.project_dir%/migrations'
    enable_profiler: false
    check_database_platform: true
    transactional: true
