## Defaults
default_user = guest
default_pass = guest
default_vhost = /

## Logging
log.console = true
log.console.level = info
log.file = false

## Memory & disk thresholds
vm_memory_high_watermark.relative = 0.75
disk_free_limit.absolute = 2GB

## Heartbeat
heartbeat = 60

## Connection
channel_max = 0
frame_max = 131072
